# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='from_user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='to_user',
            new_name='user2',
        ),
    ]
