# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180311_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user1',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user2',
            new_name='to_user',
        ),
    ]
